from pathlib import Path
import re
S=Path('site')
nav=[('index.html','Home'),('index.html#chi-sono','Chi sono'),('corsi.html','Corsi online'),('contatti.html','Contatti')]
activities=[('musicoterapia.html','Musicoterapia','Bambini, adolescenti e adulti'),('musicista.html','Musicista','Progetti e collaborazioni'),('flauto.html','Lezioni di flauto','In presenza e online')]
sections={
 'musicoterapia.html':[('percorsi','Percorsi'),('studi','Dove ricevo'),('curriculum','Curriculum'),('testimonianze','Dicono di me')],
 'musicista.html':[('progetti','Progetti e collaborazioni'),('media','Foto e video'),('curriculum','Curriculum artistico')],
 'flauto.html':[('lezioni','Metodo e lezioni'),('faq','Domande frequenti'),('testimonianze','Dicono di me')],
 'corsi.html':[('corso','Musica e respirazione')],
}
def layout(filename,title,body):
 links=''.join(f'<a href="{url}"'+(' aria-current="page"' if url==filename else '')+f'>{label}</a>' for url,label in nav)
 activity_links=''.join(f'<a href="{url}"'+(' aria-current="page"' if url==filename else '')+f'><strong>{label}</strong><span>{description}</span></a>' for url,label,description in activities)
 if filename in sections:
  page_sections=iter(sections[filename])
  def add_id(match):
   try: anchor,_=next(page_sections)
   except StopIteration:return match.group(0)
   return f'<section class="section" id="{anchor}">'
  body=re.sub(r'<section class="section"(?: id="[^"]+")?>',add_id,body)
  jump=''.join(f'<a href="#{anchor}">{label}</a>' for anchor,label in sections[filename])
  body=body.replace('</section></div>',f'<nav class="page-index" aria-label="In questa pagina"><span>In questa pagina</span>{jump}</nav></section></div>',1)
 if filename!='index.html':
  body=f'<div class="wrap breadcrumb"><a href="index.html">Home</a><span aria-hidden="true">/</span><span aria-current="page">{title}</span></div>'+body
  body=re.sub(r'<h1>(.*?)</h1>',lambda m:f'<h1 class="explicit-title">{title}</h1><p class="page-motto">{m.group(1)}</p>',body,count=1)
 else:
  choices=''.join(f'<a href="{url}"><strong>{label}</strong><span>{description}</span><b aria-hidden="true">→</b></a>' for url,label,description in activities)
  body=body.replace('<div class="actions">',f'<div class="hero-choices" aria-label="Scegli un’attività">{choices}</div><div class="actions">',1)
  body=body.replace('Scopri i percorsi','Tutte le attività',1)
 page=f'''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="Demo del sito di Yasmin Khreiwesh: musicoterapia, musica e lezioni di flauto traverso."><title>{title} · Yasmin Khreiwesh</title><link rel="icon" type="image/svg+xml" href="assets/mark.svg"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head><body><a class="skip" href="#main">Vai al contenuto</a><div class="demo-bar">ANTEPRIMA DEL SITO · Testi e fotografie dimostrativi</div><header><div class="wrap"><a class="brand" href="index.html" aria-label="Yasmin Khreiwesh, homepage"><img src="assets/mark.svg" alt=""><div><span>Dott.ssa Yasmin Khreiwesh</span><small>Musicoterapia · Musica · Flauto</small></div></a><button class="menu" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Navigazione principale">{links}</nav></div></header><main id="main">{body}</main><section class="contact"><div class="wrap"><div><div class="eyebrow">Un primo incontro</div><h2>Cominciamo dall’ascolto.</h2></div><div><p>Un percorso, una lezione o un progetto musicale: ogni incontro parte da ciò che stai cercando.</p><a class="button" href="contatti.html">Parliamone <span aria-hidden="true">→</span></a></div></div></section><footer><div class="wrap"><span>© Yasmin Khreiwesh · Demo 2026</span><span>Foto illustrative · Nessun dato raccolto · <a href="note-demo.html">Informazioni sulla demo</a></span></div></footer></body></html>'''
 page=page.replace('<header>','<header class="site-header">',1)
 page=page.replace('>Menu</button>','>Menu <span aria-hidden="true">☰</span></button>',1)
 page=page.replace('</nav></div></header>',f'</nav></div><nav class="activity-nav wrap" aria-label="Le tre attività">{activity_links}</nav></header>',1)
 footer_links=''.join(f'<a href="{url}">{label}</a>' for url,label,_ in activities)
 page=page.replace('<footer><div class="wrap">',f'<footer><div class="wrap footer-links"><a href="index.html">Home</a><a href="index.html#chi-sono">Chi sono</a>{footer_links}<a href="corsi.html">Corsi online</a><a href="contatti.html">Contatti</a></div><div class="wrap">',1)
 (S/filename).write_text(page,encoding='utf-8')
def heading(label,title,lead):return f'<div class="wrap"><section class="page-hero"><div class="eyebrow">{label}</div><h1>{title}</h1><p class="lead">{lead}</p></section></div>'
def block(title,copy):return f'<article class="editorial"><h3>{title}</h3><p>{copy}</p></article>'
layout('index.html','Home','''<div class="wrap"><section class="hero"><div><div class="eyebrow">Musica. Ascolto. Incontro.</div><h1>La musica,<br>uno spazio<br>di incontro.</h1><p>Musicoterapia, progetti musicali e lezioni di flauto: tre modi di incontrare la musica e trovare il proprio spazio di espressione.</p><div class="actions"><a class="button" href="#percorsi">Scopri i percorsi <span aria-hidden="true">↓</span></a><a class="text-link" href="#chi-sono">Conosci Yasmin</a></div></div><div class="hero-media"><img src="assets/flute-hero.jpg" alt="Dettaglio illustrativo di mani su un flauto traverso" fetchpriority="high"><div class="caption">Fotografia illustrativa, da sostituire con uno scatto di Yasmin.</div></div></section><div class="intro-line" aria-hidden="true"><img src="assets/mark.svg" alt=""></div><section class="section" id="percorsi"><div class="section-head"><div><div class="eyebrow">Tre modi di vivere la musica</div><h2>Il tuo punto di partenza.</h2></div><p>Per chi desidera un percorso personale, per chi vuole imparare e per chi cerca una collaborazione artistica.</p></div><div class="paths"><a class="path" href="musicoterapia.html"><span class="number">01</span><h3>Musicoterapia</h3><p>Percorsi per bambini, adolescenti e adulti, attraverso l’ascolto e l’esperienza musicale.</p><span class="arrow" aria-hidden="true">↗</span></a><a class="path" href="musicista.html"><span class="number">02</span><h3>Musicista</h3><p>Il flauto, i progetti, le esecuzioni e le possibilità di fare musica insieme.</p><span class="arrow" aria-hidden="true">↗</span></a><a class="path" href="flauto.html"><span class="number">03</span><h3>Lezioni di flauto</h3><p>Un percorso didattico da conoscere, in presenza oppure online.</p><span class="arrow" aria-hidden="true">↗</span></a></div></section><section class="section about-grid" id="chi-sono"><div class="about-art"><img src="assets/mark.svg" alt="Il segno musicale di Yasmin"><p class="script">Ogni persona ha<br>il proprio tempo.</p></div><div><div class="eyebrow">Chi sono</div><h2>Yasmin Khreiwesh</h2><p>Musicoterapista, flautista e insegnante di flauto. Questo sito riunisce le tre dimensioni del mio lavoro: la relazione attraverso la musica, l’esperienza artistica e l’insegnamento.</p><p class="notice">Qui inseriremo la biografia di Yasmin, la formazione e le esperienze, usando il curriculum che ci fornirà.</p><a class="text-link" href="musicoterapia.html#curriculum">Formazione e curriculum →</a></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">Da esplorare, anche a distanza</div><h2>Musica e respiro.</h2></div><div><p>Uno spazio dedicato ai futuri corsi online, con programmi, modalità e materiali.</p><a class="text-link" href="corsi.html">Esplora i corsi →</a></div></div></section></div>''')
layout('musicoterapia.html','Musicoterapia',heading('01 / Musicoterapia','Uno spazio per ascoltarsi.','Percorsi rivolti a bambini, adolescenti e adulti. Un primo incontro permette di conoscere la richiesta e approfondire modalità e obiettivi del lavoro.')+'''<div class="wrap"><section class="section"><div class="content-grid">'''+block('Bambini','Un’area per raccontare il lavoro con i più piccoli e il coinvolgimento delle famiglie. Attività, fasce d’età e modalità saranno definite con Yasmin.')+block('Adolescenti','Uno spazio per presentare i percorsi dedicati agli adolescenti, l’espressione personale e la relazione attraverso la musica.')+block('Adulti','Qui troveranno posto i percorsi per adulti, i destinatari e le modalità degli incontri individuali o di gruppo.')+block('Come si comincia','Conoscere la persona e la sua richiesta è il primo passo. Il sito definitivo spiegherà come richiedere un colloquio e come si svolge.')+'''</div></section><section class="section"><div class="eyebrow">Dove ricevo</div><h2>Luoghi per incontrarsi.</h2><div class="empty">Le fotografie degli studi, le sedi e gli orari saranno inseriti appena disponibili. Nella demo non sono presenti indirizzi fittizi.</div></section><section class="section" id="curriculum"><div class="eyebrow">Formazione</div><h2>Il percorso professionale.</h2><p>Qui sarà possibile consultare e scaricare il curriculum di Yasmin.</p><p class="notice">Curriculum da inserire: nessuna qualifica aggiuntiva o esperienza è stata inventata.</p></section><section class="section"><h2>Le parole di chi partecipa.</h2><p>Le testimonianze saranno pubblicate soltanto dopo essere state raccolte e autorizzate.</p></section></div>''')
layout('musicista.html','Musicista',heading('02 / Musicista','La musica, dal vivo.','Il flauto come voce artistica: uno spazio per le esecuzioni, i progetti e le collaborazioni di Yasmin.')+'''<div class="wrap"><img class="wide-photo" src="assets/flute-hero.jpg" alt="Fotografia illustrativa di un flauto traverso"><p class="caption">Immagine illustrativa. La galleria conterrà fotografie e video originali.</p><section class="section"><div class="content-grid">'''+block('Progetti musicali','Ogni progetto avrà una presentazione, i musicisti coinvolti e i materiali per ascoltarlo. Queste informazioni saranno curate con Yasmin.')+block('Servizi e collaborazioni','Un’area per presentare le proposte musicali disponibili e ricevere richieste da organizzatori, associazioni e altri musicisti.')+'''</div></section><section class="section"><h2>Guarda, ascolta, conosci.</h2><div class="empty">Foto e video delle esecuzioni saranno inseriti qui. Non utilizziamo registrazioni di altri artisti come se fossero di Yasmin.</div></section><section class="section"><h2>Curriculum artistico.</h2><p>Il curriculum artistico sarà consultabile e scaricabile in questa sezione.</p><a class="button" href="contatti.html">Proponi una collaborazione <span aria-hidden="true">→</span></a></section></div>''')
layout('flauto.html','Lezioni di flauto',heading('03 / Insegnamento','Il tuo tempo, il tuo suono.','Lezioni di flauto traverso per conoscere lo strumento e costruire un percorso musicale. Metodo, offerta e modalità saranno raccontati con le parole di Yasmin.')+'''<div class="wrap"><section class="section"><div class="content-grid">'''+block('Il metodo didattico','Qui presenteremo il metodo di Yasmin: come organizza le lezioni e come accompagna lo studente nell’ascolto, nel respiro e nello studio dello strumento.')+block('Lezioni in presenza','Questa sezione conterrà sedi, destinatari, frequenza e modalità delle lezioni. Le informazioni organizzative sono da confermare.')+block('Lezioni online','Una possibilità da descrivere nel sito definitivo, con strumenti necessari, durata e modalità di collegamento.')+block('Formazione e offerta','Curriculum didattico, corsi disponibili ed eventuali laboratori saranno inseriti dopo la raccolta dei materiali.')+'''</div></section><section class="section"><h2>Prima di cominciare.</h2><details><summary>A che età si può iniziare?</summary><p>Dipende dal percorso e dallo strumento adatto alla persona. Nella versione definitiva Yasmin indicherà le fasce d’età delle sue proposte e le possibilità per i più piccoli.</p></details><details><summary>Devo avere già un flauto?</summary><p>È utile confrontarsi con l’insegnante prima di un acquisto. Yasmin potrà spiegare quale strumento serve per iniziare e se sono previste alternative per la prima lezione.</p></details><details><summary>Quanto costa un flauto?</summary><p>Il prezzo dipende dal modello e dalla scelta tra nuovo e usato. Qui inseriremo indicazioni aggiornate e concordate con Yasmin, senza suggerire un acquisto prima di conoscere le esigenze dello studente.</p></details><details><summary>Come funzionano le lezioni online?</summary><p>Durata, piattaforma, attrezzatura e disponibilità saranno definite da Yasmin e pubblicate in questa sezione.</p></details><details><summary>Posso iniziare anche da adulto?</summary><p>Questa richiesta può essere approfondita con Yasmin per conoscere l’offerta e il percorso più adatto.</p></details></section><section class="section"><h2>Esperienze da condividere.</h2><p>Qui inseriremo le testimonianze degli studenti che desiderano raccontare il proprio percorso.</p></section></div>''')
layout('corsi.html','Corsi online',heading('Corsi online','Porta l’ascolto con te.','Uno spazio per i corsi da seguire a distanza. Nella prima versione presenteremo programmi e modalità; gli acquisti e l’area riservata arriveranno in una fase successiva.')+'''<div class="wrap"><section class="section"><div class="tag">In preparazione</div><h2 class="space">Musica e respirazione.</h2><p>Un corso sulla respirazione è tra i contenuti previsti da Yasmin. Programma, durata, materiali e destinatari sono ancora da definire.</p><div class="content-grid space">'''+block('Cosa troverai','Una presentazione chiara del programma, delle modalità di fruizione e dei materiali inclusi.')+block('Quando sarà disponibile','La data e le modalità di partecipazione saranno comunicate quando i contenuti saranno pronti.')+'''</div><a class="button" href="contatti.html">Chiedi informazioni <span aria-hidden="true">→</span></a><p class="notice space">La demo non prevede acquisti, pagamenti o account. Non sono pubblicati prezzi o date provvisori.</p></section></div>''')
layout('contatti.html','Contatti',heading('Contatti','Raccontami cosa cerchi.','Un percorso di musicoterapia, una lezione di flauto o una collaborazione musicale: da qui potrai contattare Yasmin.')+'''<div class="wrap"><section class="section content-grid"><div><h2>Un primo passo.</h2><p>I recapiti e le sedi saranno inseriti dopo la conferma di Yasmin.</p><p class="notice">Questo è un modulo dimostrativo. Non invia messaggi e non salva i dati inseriti.</p><p class="small">Per provare la demo usa informazioni inventate.</p></div><form class="form-demo"><div><label for="name">Nome</label><input id="name" autocomplete="off" placeholder="Il tuo nome (di esempio)" required></div><div><label for="interest">Di cosa vorresti parlare?</label><textarea id="interest" rows="4" placeholder="Una lezione, un percorso, un progetto…" required></textarea></div><button class="button" type="submit">Prova il modulo <span aria-hidden="true">→</span></button><div class="form-message" role="status" hidden></div></form></section></div>''')
layout('note-demo.html','Informazioni sulla demo',heading('Anteprima','Una proposta da esplorare.','Questa demo mostra struttura e direzione visiva del futuro sito di Yasmin.')+'''<div class="wrap"><section class="section"><h3>Contenuti provvisori</h3><p>Testi, fotografia e ricostruzione vettoriale del segno musicale sono dimostrativi. Prima del lancio saranno sostituiti o confermati insieme a Yasmin. Non sono presenti testimonianze, sedi o curriculum inventati.</p><h3>Tipografia</h3><p>Allura è utilizzato per la firma e i titoli brevi. Manrope è l’alternativa temporanea a Nourd, in attesa del font con licenza per il web.</p><h3>Dati e servizi</h3><p>Il modulo è locale e non invia o conserva dati. Non sono integrati analytics, video esterni, pagamenti o cookie del sito. Il servizio di hosting GitHub Pages può gestire dati tecnici secondo la propria informativa.</p><h3>Versione definitiva</h3><p>Recapiti, materiali originali, testi approvati e informazioni privacy saranno completati prima di attivare servizi di contatto o vendita.</p></section></div>''')
print('Generated 7 demo pages')
